"""add_queued_to_jobstatus

Revision ID: 361f9d528151
Revises: 85b1c5708052
Create Date: 2026-08-30 19:52:38.978785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '361f9d528151'
down_revision: Union[str, Sequence[str], None] = '85b1c5708052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE jobstatus ADD VALUE IF NOT EXISTS 'QUEUED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
